#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${LANDMARKS_DATABASE_USER} WITH PASSWORD '${LANDMARKS_DATABASE_PASSWORD}';
    CREATE DATABASE ${LANDMARKS_DATABASE_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${LANDMARKS_DATABASE_NAME} TO ${LANDMARKS_DATABASE_USER};
EOSQL
